apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
      - image: redis
        name: redis-client
