apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-service
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 5000 # external
    targetPort: 5000 # internal
  type: NodePort